modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="fracturedlands"
version="${file.jarVersion}"
displayName="Fractured Lands"
description='''
Transforms the overworld into an expansive underground cave realm.
All biomes spawn naturally in caves with proper features, structures, and vegetation.
Compatible with all biome mods - BiomesOPlenty, Terralith, Oh The Biomes You'll Go, etc.
'''
logoFile="logo.png"
credits="Inspired by cave compact datapacks"
authors="smokydastona"

[[dependencies.fracturedlands]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="SERVER"

[[dependencies.fracturedlands]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.fracturedlands]]
modId="terrablender"
mandatory=true
versionRange="[3.0.1.4,)"
ordering="AFTER"
side="SERVER"